### ISSUE TITLE
Renders differently in Firefox

### ISSUE THREAD

**Issue by realripley00** [OpusCapita/react-searchbar#14]
This obviously isn't a huge deal, but for me the component seems to render differently in Firefox compared to other browsers. Any idea why that would be/what would cause it?

Using it pretty straightforwardly:
<SearchBar
                            onSearch={this.handleSearch}
                            value={this.state.searchValue}
                            onChange={(i) => {this.changeSearch(i)}} />

and here is how it looks in Chrome/everywhere else:

![screen shot 2018-11-07 at 2 19 44 pm](https://user-images.githubusercontent.com/23426271/48155115-44160400-e298-11e8-86db-11b56f3eacf3.png)

Here is how it looks in Firefox:

![screen shot 2018-11-07 at 2 19 50 pm](https://user-images.githubusercontent.com/23426271/48155129-4e380280-e298-11e8-8b3f-9ec94af083be.png)

**Comment by bo-kh** [comment]
That is pretty weird. That is what I see in Firefox  63.0.1 when I ran a demo from this repo:
 
![image](https://user-images.githubusercontent.com/17910553/48334659-19df9000-e664-11e8-85b6-dce1ce920677.png)

It looks exactly the same way like in other browsers. It doesn't look as an issue..

**Comment by realripley00** [comment]
Weird. It must be something specific to my project because I tried adding it to a different, simpler one and it doesn't look like that. Thanks!
