### ISSUE TITLE
dynamicSearchStartsFrom can't be zero

### ISSUE THREAD

**Issue by naniantero** [OpusCapita/react-searchbar#4]
At the moment dynamicSearchStartsFrom prop can't be zero. This becomes a problem in case I want to filter a collection dynamically and want to return the original, unfiltered collection if search field is empty.

In following code example onSearchChange doensn't fire if value.length === 0:

```
onSearchChange = (value) => {
    this.setState({ search: value });
  };

  getFilteredStuff = () => {
    if (!this.state.search) return this.props.all;
    return this.props.all.filter(item => /* something*/);
  };
```

**Comment by skarjalainen** [comment]
Fixed in #15
